# Generated by Django 3.2 on 2022-12-28 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carriers',
            name='resume',
            field=models.FileField(upload_to='resume'),
        ),
    ]
